name: Publish package
on:
  push:
    branches:
    - master
jobs:
  publish:
    runs-on:
    - self-hosted
    - vm:t3.micro
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i -g npm@7
    - run: npm ci
    - run: npm test
    - run: npm pack
    - run: npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}